// src/constants/subcategoryConstants.js

export const SUBCATEGORY_LIST_REQUEST = 'SUBCATEGORY_LIST_REQUEST';
export const SUBCATEGORY_LIST_SUCCESS = 'SUBCATEGORY_LIST_SUCCESS';
export const SUBCATEGORY_LIST_FAIL = 'SUBCATEGORY_LIST_FAIL';

export const SUBCATEGORY_ADD_REQUEST = 'SUBCATEGORY_ADD_REQUEST';
export const SUBCATEGORY_ADD_SUCCESS = 'SUBCATEGORY_ADD_SUCCESS';
export const SUBCATEGORY_ADD_FAIL = 'SUBCATEGORY_ADD_FAIL';

export const SUBCATEGORY_REMOVE_REQUEST = 'SUBCATEGORY_REMOVE_REQUEST';
export const SUBCATEGORY_REMOVE_SUCCESS = 'SUBCATEGORY_REMOVE_SUCCESS';
export const SUBCATEGORY_REMOVE_FAIL = 'SUBCATEGORY_REMOVE_FAIL';
